### ISSUE TITLE
-opt:l:inline errors with an encoding error

### ISSUE THREAD

**Issue by Marcus-Rosti** [bazelbuild/rules_scala#1028]
When registering a new toolchain -opt:l:inline errors with an encoding error
```
$ bazel build --sandbox_debug //src/main/scala/...
INFO: Invocation ID: b0d9f6da-20ed-44fd-88a3-29ef23f3505a
INFO: Analyzed 4 targets (1 packages loaded, 12 targets configured).
INFO: Found 4 targets...
ERROR: /private/var/tmp/_bazel_mrosti/bebc6e079c4eb718c314a8e1b83998a4/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD:5:1: Couldn't build file external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/scala_version.jar: scala @io_bazel_rules_scala//third_party/dependency_analyzer/src/main:scala_version failed (Exit 1): scalac failed: error executing command 
  (cd /private/var/tmp/_bazel_mrosti/bebc6e079c4eb718c314a8e1b83998a4/execroot/caprica && \
  exec env - \
  bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/scala_version_scalac_worker_input)
Execution platform: @local_config_platform//:host
error: IO error while decoding inline with UTF-8: inline (No such file or directory)
Please try specifying another one using the -encoding option
one error found
one error found
java.lang.RuntimeException: Build failed
        at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:256)
        at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:76)
        at io.bazel.rulesscala.worker.GenericWorker.runPersistentWorker(GenericWorker.java:45)
        at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:111)
        at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
INFO: Elapsed time: 0.391s, Critical Path: 0.13s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

```
load("@io_bazel_rules_scala//scala:scala_toolchain.bzl", "scala_toolchain")
scala_toolchain(
    name = "my_toolchain_impl",
    scalacopts = [
#        "-encoding", "utf8",
        "-Xlint",
        "-explaintypes",
        "-feature",
        "-unchecked",
        "-deprecation",
        "-Ywarn-unused",
        "-opt:l:method",
        "-opt-inline-from:**",
    ],
    unused_dependency_checker_mode = "error",
    visibility = ["//visibility:public"]
)

toolchain(
    name = "my_scala_toolchain",
    toolchain_type = "@io_bazel_rules_scala//scala:toolchain_type",
    toolchain = "my_toolchain_impl",
    visibility = ["//visibility:public"]
)
```

**Comment by ittaiz** [comment]
this [post](https://www.lightbend.com/blog/scala-inliner-optimizer) seems to suggest you're using the wrong syntax.
You need :
```
scalacopts = [
#        "-encoding", "utf8",
        "-Xlint",
        "-explaintypes",
        "-feature",
        "-unchecked",
        "-deprecation",
        "-Ywarn-unused",
        "-opt:l:method",
        "-opt:l:inline",  #this is what you're missing
        "-opt-inline-from:**",
    ],
```

If you need further assistance please send a repro

**Comment by ittaiz** [comment]
Closing. Please reopen if there is a bug relating to rules_scala itself
