### ISSUE TITLE
scalapb_proto_library fails when bazel sandboxing is enabled

### ISSUE THREAD

**Issue by muditmalpani** [bazelbuild/rules_scala#1086]
**Problem**:
I'm trying to build the following build file:

```
load('@io_bazel_rules_scala//scala_proto:scala_proto.bzl', 'scala_proto_library')

proto_library(
  name = "snapshot_lib",
  srcs = ["snapshot.proto"],
  visibility = ["//visibility:public"],
)

scala_proto_library(
  name = "snapshot_scala",
  deps = [":snapshot_lib"],
  visibility = ["//visibility:public"],
)
```

The build succeeds when I'm not using bazel sandbox, but when sandbox is enabled I'm getting the following error:

```
$ bazel build  //src/grpc/snapshot:snapshot_scala
WARNING: The following configs were expanded more than once: [read_only_remote_cache, remote_cache]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Writing tracer profile to '/home/ubuntu/.cache/bazel/_bazel_ubuntu/56d8737af03a66ea9e9f9d3b0c946228/command.profile.gz'
INFO: Invocation ID: ab1153c4-97d6-4df9-8af2-42b17baae506
WARNING: The following configs were expanded more than once: [read_only_remote_cache, remote_cache]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Writing tracer profile to '/home/ubuntu/.cache/bazel/_bazel_ubuntu/56d8737af03a66ea9e9f9d3b0c946228/command.profile.gz'
INFO: Invocation ID: 9aba6dd8-95cb-4f5e-a74c-1211a3e41126
INFO: Reading 'startup' options from /home/ubuntu/repos/master/.bazelrc: --host_jvm_args=-Dbazel.DigestFunction=sha256
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=270
INFO: Reading rc options for 'build' from /home/ubuntu/repos/master/.bazelrc:
  'build' options: --action_env=PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin --compilation_mode=opt --strip=never --features per_object_debug_info --fission=yes --features -supports_pic --dynamic_mode=fully --worker_verbose --worker_sandboxing --worker_quit_after_build --output_filter=DONT_MATCH_ANYTHING --announce_rc --jobs=4
INFO: Reading rc options for 'build' from /home/ubuntu/repos/master/wrapper.bazelrc:
  'build' options: --config=read_only_remote_cache --action_env=TOOLCHAIN_ACTION_ENV_HASH=f118f34ebf55a977c062390bf0740ddca7ca6bf69a1ecefb25c2844ec83057a3
INFO: Reading rc options for 'build' from /home/ubuntu/repos/master/user.bazelrc:
  'build' options: --config=read_only_remote_cache
INFO: Found applicable config definition build:read_only_remote_cache in file /home/ubuntu/repos/master/.bazelrc: --config=remote_cache --remote_upload_local_results=false --remote_accept_cached=true
INFO: Found applicable config definition build:remote_cache in file /home/ubuntu/repos/master/.bazelrc: --remote_http_cache=https://bazel-cache.xyz.com:443/bionic/cache --experimental_strict_action_env --remote_timeout=10 --remote_local_fallback=true
INFO: Found applicable config definition build:read_only_remote_cache in file /home/ubuntu/repos/master/.bazelrc: --config=remote_cache --remote_upload_local_results=false --remote_accept_cached=true
INFO: Found applicable config definition build:remote_cache in file /home/ubuntu/repos/master/.bazelrc: --remote_http_cache=https://bazel-cache.xyz.com:443/bionic/cache --experimental_strict_action_env --remote_timeout=10 --remote_local_fallback=true
INFO: Analyzed target //src/grpc/snapshot:snapshot_scala (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Created new sandboxed ProtoScalaPBRule worker (id 13), logging to /home/ubuntu/.cache/bazel/_bazel_ubuntu/56d8737af03a66ea9e9f9d3b0c946228/bazel-workers/worker-13-ProtoScalaPBRule.log
INFO: Destroying ProtoScalaPBRule worker (id 13)
ERROR: /home/ubuntu/repos/master/src/grpc/snapshot/BUILD.bazel:3:1: creating scalapb files //src/grpc/snapshot:snapshot_lib failed: IOException while preparing the execution environment of a worker:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Cannot run program "/home/ubuntu/.cache/bazel/_bazel_ubuntu/56d8737af03a66ea9e9f9d3b0c946228/bazel-workers/worker-13-ProtoScalaPBRule/com_snapshot/bazel-out/host/bin/external/io_bazel_rules_scala/src/scala/scripts/scalapb_generator" (in directory "/home/ubuntu/.cache/bazel/_bazel_ubuntu/56d8737af03a66ea9e9f9d3b0c946228/bazel-workers/worker-13-ProtoScalaPBRule/com_snapshot"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory.start(JavaSubprocessFactory.java:141)
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory.create(JavaSubprocessFactory.java:162)
	at com.google.devtools.build.lib.shell.SubprocessBuilder.start(SubprocessBuilder.java:232)
        ....
```

It looks to me that the bazel sandbox is not getting access to the `scalapb_generator` tool. Is this a bug in the scala_proto_toolchain, or am I making some error in the configuration?

**Platform**: Ubuntu 18.04

**Comment by muditmalpani** [comment]
Upgrading to latest version of bazel fixed the issue. Closing this.
