### ISSUE TITLE
Coverage fails if a scala_binary target is included

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#1169]
I am running coverage on my project with "//..." (including some filters), and so far this was working.

After d074d87c254a8e720568989cb455f43508819927 this causes an error:

```
ERROR: myproject/BUILD:144:13: in scala_binary rule //abc:def: 
Traceback (most recent call last):
	File "/myproject/1234567789/external/io_bazel_rules_scala/scala/private/rules/scala_binary.bzl", line 31, column 22, in _scala_binary_impl
		return run_phases(
	File "/myproject/1234567789/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 70, column 32, in run_phases
		new_provider = function(ctx, current_provider)
	File "/myproject/1234567789/external/io_bazel_rules_scala/scala/private/phases/phase_write_executable.bzl", line 50, column 43, in phase_write_executable_common
		return _phase_write_executable_default(ctx, p)
	File "/myproject/1234567789/external/io_bazel_rules_scala/scala/private/phases/phase_write_executable.bzl", line 53, column 35, in _phase_write_executable_default
		return _phase_write_executable(
	File "/myproject/1234567789/external/io_bazel_rules_scala/scala/private/phases/phase_write_executable.bzl", line 73, column 45, in _phase_write_executable
		return _write_executable_non_windows(ctx, executable, rjars, main_class, jvm_flags, wrapper)
	File "/myproject/1234567789/external/io_bazel_rules_scala/scala/private/phases/phase_write_executable.bzl", line 110, column 82, in _write_executable_non_windows
		["${RUNPATH}%s" % (j.short_path) for j in rjars.to_list() + ctx.files._jacocorunner],
Error: No attribute '_jacocorunner' in files. Make sure there is a label or label_list type attribute with this name
Available attributes: _action_listener, _code_coverage_instrumentation_worker, _config_dependencies, _dependency_analyzer_plugin, _exe, _host_javabase, _java_runtime, _java_stub_template, _java_toolchain, _phase_providers, _scala_toolchain, _scalac, _singlejar, _zipper, applicable_licenses, classpath_resources, compatible_with, data, deps, exec_compatible_with, plugins, resource_jars, resources, restricted_to, runtime_deps, srcs, toolchains, unused_dependency_checker_ignored_targets
```

Is that the case that before d074d87c254a8e720568989cb455f43508819927 this common code in phase_write_executable for scala_binary was not executing? (as _jacocorunner seems to be there for longer)

**Comment by liucijus** [comment]
Thanks for reporting, @gergelyfabian!

**Comment by liucijus** [comment]
Turns out older code always had `use_jacoco = False` for non scala test rules.
Question, do we want coverage instrumentation from other executables than test rules? I think it can be useful if for some reason someone wants to run coverage instrumentation not from the test.
Making non test rules being able to collect coverage would mean that #1163 `jacocorunner` should be available via `scala_toolchain`.

**Comment by gergelyfabian** [comment]
> Turns out older code always had `use_jacoco = False` for non scala test rules.
> Question, do we want coverage instrumentation from other executables than test rules? I think it can be useful if for some reason someone wants to run coverage instrumentation not from the test.

It could be ok, but I think scala_binary would need to work also if it happens to be listed as a target when running `bazel coverage`.

> Making non test rules being able to collect coverage would mean that #1163 `jacocorunner` should be available via `scala_toolchain`.

Yes, as it would need to be configurable for more target types (binary, library, test, etc.).
