### ISSUE TITLE
scalac compiler classpath extensions

### ISSUE THREAD

**Issue by gergelyfabian** [bazelbuild/rules_scala#1299]
There is a wartremover plugin for scalac, with an easy-to-use sbt plugin.
It can be also added with Bazel (example in https://github.com/digital-asset/daml/blob/main/BAZEL-JVM.md#compiler-plugins).

I'd have a question related to an advanced usage, adding custom warts, that would require changing scalac's classpath to make those warts usable by scalac:

Example for sbt:
```scala
libraryDependencies += "myOrg" %% "myWartPackage" % "1.0.0"
wartremoverClasspaths ++= {
  (dependencyClasspath in Compile).value.files
    .find(_.name.contains("myWartPackage"))
    .map(_.toURI.toString)
    .toList
}
```

From: https://www.wartremover.org/doc/adding-your-own-warts.html

Is there an equivalent for rules_scala, to add certain dependencies for scalac's classpath?

**Comment by liucijus** [comment]
You can configure [custom scala toolchain](https://github.com/liucijus/rules-scala-proto-toolchain/blob/main/BUILD#L10) with custom deps provider for scalac classpath, if that's what you are looking for.

**Comment by liucijus** [comment]
@gergelyfabian if you succeed, would be interested to hear about what needed to be done.

**Comment by gergelyfabian** [comment]
@liucijus, of course will do :)

**Comment by Vanessamae23** [comment]
@gergelyfabian I am so sorry i know this issue is closed but I am still facing issue trying to get wartremover and bazel running for custom warts..

I have sort of followed the one u suggested but I keep on getting 

```scala
Ignoring duplicate plugin wartremover (org.wartremover.Plugin)
error: scala.ScalaReflectionException: object com.linters.NoSysError not found.
        at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:190)
        at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:29)
        at org.wartremover.Plugin.getTraverser(Plugin.scala:20)
        at org.wartremover.Plugin.$anonfun$processOptions$2(Plugin.scala:41)
        at sc
```

Not sure if this was the one you encountered but this PR was definitely a long time ago, not sure if you could remember
