### ISSUE TITLE
Error in fail: specs2_classpath requires mapping of specs2_classpath provider id on the toolchain @io_bazel_rules_scala//testing/toolchain:testing_toolchain_type

### ISSUE THREAD

**Issue by agluszak** [bazelbuild/rules_scala#1363]
I encountered this problem when I tried to use `scala_specs2_junit_test`

```
andrzej@MUNIT-521 ~/c/b/spec2_repro (main)> bazel build //...
ERROR: /home/andrzej/.cache/bazel/_bazel_andrzej/5b25ff80b1206a11fa6f7f8aa5132ba7/external/io_bazel_rules_scala/testing/toolchain/BUILD:20:23: in testing_toolchain_deps rule @io_bazel_rules_scala//testing/toolchain:specs2_classpath: 
Traceback (most recent call last):
	File "/home/andrzej/.cache/bazel/_bazel_andrzej/5b25ff80b1206a11fa6f7f8aa5132ba7/external/io_bazel_rules_scala/testing/toolchain/toolchain_deps.bzl", line 9, column 33, in _testing_toolchain_deps
		return expose_toolchain_deps(ctx, _toolchain_type)
	File "/home/andrzej/.cache/bazel/_bazel_andrzej/5b25ff80b1206a11fa6f7f8aa5132ba7/external/io_bazel_rules_scala/scala/private/toolchain_deps/toolchain_deps.bzl", line 22, column 34, in expose_toolchain_deps
		deps_info = find_deps_info_on(ctx, toolchain_type_label, deps_id)
	File "/home/andrzej/.cache/bazel/_bazel_andrzej/5b25ff80b1206a11fa6f7f8aa5132ba7/external/io_bazel_rules_scala/scala/private/toolchain_deps/toolchain_deps.bzl", line 18, column 34, in find_deps_info_on
		return _lookup_provider_by_id(ctx, toolchain_type_label, dep_providers, deps_id)[DepsInfo]
	File "/home/andrzej/.cache/bazel/_bazel_andrzej/5b25ff80b1206a11fa6f7f8aa5132ba7/external/io_bazel_rules_scala/scala/private/toolchain_deps/toolchain_deps.bzl", line 13, column 9, in _lookup_provider_by_id
		fail(_required_deps_id_message(ctx.attr.name, toolchain_type_label, deps_id))
Error in fail: specs2_classpath requires mapping of specs2_classpath provider id on the toolchain @io_bazel_rules_scala//testing/toolchain:testing_toolchain_type
ERROR: Analysis of target '//example:example-spec2-test' failed; build aborted: Analysis of target '@io_bazel_rules_scala//testing/toolchain:specs2_classpath' failed
INFO: Elapsed time: 0.053s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

To reproduce clone https://github.com/agluszak/bazel-spec2-repro and run `bazel build //...`

**Comment by liucijus** [comment]
Your [workspace](https://github.com/agluszak/bazel-spec2-repro/blob/main/WORKSPACE#L45-L49)  is configured to load default ScalaTest deps toolchain. For Specs2 you need to have Specs2/JUnit deps toolchain. Please check examples how to do that: https://github.com/bazelbuild/rules_scala/tree/master/examples/testing. Let me know if it helps!

**Comment by agluszak** [comment]
@liucijus thanks for your reply! the problem for us is that we'd like to have both scalatest and specs2 tests in the same workspace. I updated the repro repo accordingly. The error message stays the same

**Comment by liucijus** [comment]
@agluszak to get Specs2 and ScalaTest support, you need to define custom deps toolchain, which has dependecies for both frameworks. Example is [here](https://github.com/bazelbuild/rules_scala/tree/master/examples/testing/multi_frameworks_toolchain).

**Comment by agluszak** [comment]
Great, thanks!
