### ISSUE TITLE
too many java sources can cause build to fail

### ISSUE THREAD

**Issue by softprops** [bazelbuild/rules_scala#151]
For those running mixed scala/java builds you can currently run into a limit javac places on the length of its command line.

```
java.io.IOException: Cannot run program "external/local_jdk/bin/javac": error=7, Argument list too long
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at io.bazel.rulesscala.scalac.ScalacProcessor.compileJavaSources(ScalacProcessor.java:201)
    at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:96)
    at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:125)
    at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:42)
Caused by: java.io.IOException: error=7, Argument list too long
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 4 more
```

sbt works around this by using a feature of javac that lets you provide arguments in an [arg file](https://github.com/sbt/sbt/blob/0.13/compile/src/main/scala/sbt/compiler/javac/ForkedJava.scala#L17)

It should be pretty straight foward to add that, though it may also be worth while seeing if there is something that can be borrowed from bazels built-in javac support. I did a little of splunking myself and found [this](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileAction.java#L1114-L1121) Im not sure how reusable (or accessible) that is here but its worth taking note of the behavior java_xxx rules exhibit.

**Comment by softprops** [comment]
Making a special note this limit seems variable based on platform. It was observed on osx but appears the same list of files was not hit on linux. It may just be a generally safe practice to just default to the arg file like sbt

**Comment by johnynek** [comment]
closing this until we see evidence that #155 didn't fix it.

**Comment by softprops** [comment]
Fixed it for us ;)
