### ISSUE TITLE
Failing with bazel 0.6

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_scala#284]
When using the Scala rules with Bazel 0.6, I get this error:
```
Traceback (most recent call last):
	File "/tmp/bzl/BUILD", line 14
		scala_binary(name = 'sc')
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/1cf9e271f53a4fcee3da31675bf7c3a0/external/io_bazel_rules_scala/scala/scala.bzl", line 506, in _scala_binary_impl
		_scala_binary_common(ctx, cjars, transitive_rjars)
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/1cf9e271f53a4fcee3da31675bf7c3a0/external/io_bazel_rules_scala/scala/scala.bzl", line 469, in _scala_binary_common
		_compile_or_empty(ctx, cjars, [], False)
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/1cf9e271f53a4fcee3da31675bf7c3a0/external/io_bazel_rules_scala/scala/scala.bzl", line 265, in _compile_or_empty
		_compile(ctx, jars, srcjars, buildijar)
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/1cf9e271f53a4fcee3da31675bf7c3a0/external/io_bazel_rules_scala/scala/scala.bzl", line 162, in _compile
		set((srcjars + list(dep_srcjars)))
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
```

Workaround is simple (specify `--incompatible_disallow_set_constructor=false`), but it would be nice to update the code. Ideally, it would build even with `--all_incompatible_changes`. See https://docs.bazel.build/versions/master/skylark/backward-compatibility.html for background.

Let me know if you need help.

**Comment by katre** [comment]
I filed https://github.com/bazelbuild/rules_scala/issues/280 about this 3
days ago.

**Comment by johnynek** [comment]
line 162 does not have a set on it in master. Are you using the latest master?

**Comment by johnynek** [comment]
sent this: https://github.com/bazelbuild/rules_scala/pull/285 to test on 0.6.0 to make sure it works.

**Comment by johnynek** [comment]
closing, since I think this is only true of an older version of these rules.

Please re-open if you disagree.
