### ISSUE TITLE
No way to include other scala deps to support additional Scala types.

### ISSUE THREAD

**Issue by BlueDragonX** [bazelbuild/rules_scala#316]
We have this `events.proto` file:
```
syntax = "proto3";

package zenreach.common;

option go_package = "github.com/zenreach/platypus/platform/common/protobuf";
option java_package = "com.zenreach.common";

import "google/protobuf/timestamp.proto";
import "scalapb/scalapb.proto";

option (scalapb.options) = {
    import: "com.zenreach.data.types.ProtobufConversions._"
};

// EventSource describes the source of an event.
message EventSource {
    // The UUID of the instance that sent the event.
    bytes id = 1 [(scalapb.field).type = "java.util.UUID"];

    // The name of the process that sent the event.
    string name = 2;
}

message EventMeta {
    // The ID of the event. A byte encoded UUID.
    bytes id = 1 [(scalapb.field).type = "java.util.UUID"];

    // The time of the event.
    google.protobuf.Timestamp time = 2;

    // The source of the event.
    EventSource source = 3;
}
```

As you can see we import our own `com.zenreach.data.types` package. We do this in a number of our existing proto files. Attempting to build this with `scalapb_proto_library` fails as it cannot reference that import. Attempting to provide that package as a dependency is impossible as `scalapb_proto_library` only allows `proto_library` and/or `java_proto_library` as dependencies.

**Comment by BlueDragonX** [comment]
`BUILD` file:
```
load("@io_bazel_rules_scala//scala_proto:scala_proto.bzl", "scalapb_proto_library")

proto_library(
    name = "common_proto",
    srcs = glob(["**/*.proto"]),
    visibility = ["//visibility:public"],
    deps = [
        "//scalapb:scalapb_proto",
        "//google/protobuf:timestamp_proto",
    ],
)

scalapb_proto_library(
    name = "common_scala_proto",
    with_flat_package = True,
    deps = [
        ":common_proto",
    ],
)
```

And the output of `bazel build --verbose_failures common:common_scala_proto`:
```
INFO: Found 1 target...
INFO: From creating scalapb files //common:common_scala_proto_srcjar:
@bazel-out/local-fastbuild/bin/common/common_scala_proto_srcjar_worker_input
protoc-jar: protoc version: 320, detected platform: linux/amd64
protoc-jar: executing: [/tmp/protocjar307955749194902238/bin/protoc.exe, --plugin=protoc-gen-scala=/tmp/protocbridge153355642545451688, --scala_out=flat_package:/tmp/bazelscalapb8770993627894875792, -Icommon/events.proto=common/events.proto, -Iscalapb/scalapb.proto=scalapb/scalapb.proto, -Igoogle/protobuf/descriptor.proto=google/protobuf/descriptor.proto, -Igoogle/protobuf/timestamp.proto=google/protobuf/timestamp.proto, common/events.proto, scalapb/scalapb.proto, google/protobuf/descriptor.proto, google/protobuf/timestamp.proto]
ERROR: /home/sadpengu/Work/src/github.com/zenreach/platypus/protocols/common/BUILD:22:1: scala //common:common_scala_proto failed (Exit 1): scalac failed: error executing command 
  (cd /home/sadpengu/.cache/bazel/_bazel_sadpengu/d2d05fc8812ceca219eece2a81acf47e/execroot/com_github_zenreach_platypus_protocols && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/local-fastbuild/bin/common/common_scala_proto_worker_input)

Use --sandbox_debug to see verbose messages from the sandbox.
bazel-out/local-fastbuild/bin/common/tmp5317277876742884681/com/zenreach/common/EventMeta.scala:9: error: object data is not a member of package com.zenreach
import com.zenreach.data.types.ProtobufConversions._
                    ^
bazel-out/local-fastbuild/bin/common/tmp5317277876742884681/com/zenreach/common/EventSource.scala:9: error: object data is not a member of package com.zenreach
import com.zenreach.data.types.ProtobufConversions._
                    ^
bazel-out/local-fastbuild/bin/common/tmp5317277876742884681/com/zenreach/common/EventsProto.scala:9: error: object data is not a member of package com.zenreach
import com.zenreach.data.types.ProtobufConversions._
                    ^
bazel-out/local-fastbuild/bin/common/tmp5317277876742884681/com/zenreach/common/EventMeta.scala:164: error: No TypeMapper found for conversion between com.google.protobuf.ByteString and java.util.UUID.
    Try to implement an implicit TypeMapper[com.google.protobuf.ByteString, java.util.UUID]. You can implement it
    in java.util.UUID companion class.
    Alternatively you can import this implicit using file-level Scala imports (see documentation)

  private val _typemapper_id: _root_.com.trueaccord.scalapb.TypeMapper[_root_.com.google.protobuf.ByteString, java.util.UUID] = implicitly[_root_.com.trueaccord.scalapb.TypeMapper[_root_.com.google.protobuf.ByteString, java.util.UUID]]
                                                                                                                                          ^
bazel-out/local-fastbuild/bin/common/tmp5317277876742884681/com/zenreach/common/EventSource.scala:137: error: No TypeMapper found for conversion between com.google.protobuf.ByteString and java.util.UUID.
    Try to implement an implicit TypeMapper[com.google.protobuf.ByteString, java.util.UUID]. You can implement it
    in java.util.UUID companion class.
    Alternatively you can import this implicit using file-level Scala imports (see documentation)

  private val _typemapper_id: _root_.com.trueaccord.scalapb.TypeMapper[_root_.com.google.protobuf.ByteString, java.util.UUID] = implicitly[_root_.com.trueaccord.scalapb.TypeMapper[_root_.com.google.protobuf.ByteString, java.util.UUID]]
                                                                                                                                          ^
5 errors found
5 errors found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:256)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:68)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:125)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
Target //common:common_scala_proto failed to build
INFO: Elapsed time: 9.792s, Critical Path: 9.69s
```

**Comment by johnynek** [comment]
Cc @azymnis who may have work arounds

**Comment by nmurthy** [comment]
thanks @johnynek and @azymnis! lol, it's funny i'm still relying on your libraries and help after all these years :)

**Comment by azymnis** [comment]
Ah the way I implemented this you can’t have Scala deps. I can fix that

**Comment by nmurthy** [comment]
damn @azymnis, thanks for the super quick PR!

**Comment by BlueDragonX** [comment]
Thank @azymnis.

I tried the branch in that PR and added `//types` to `common_scala_proto`:
```
scalapb_proto_library(
    name = "common_scala_proto",
    with_flat_package = True,
    deps = [
        "//types",
        ":common_proto",
    ],
)
```

That resolved the import issues but gave me a bunch of other errors. Here's the output of `bazel build common:common_scala_proto`:
```
INFO: Found 1 target...
ERROR: /home/sadpengu/Work/src/github.com/zenreach/platypus/protocols_builtin/common/BUILD:22:1: scala //common:common_scala_proto failed (Exit 1).
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/EnumOptions.scala:35: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/EnumOptions.scala:58: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/EnumValueOptions.scala:30: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/EnumValueOptions.scala:50: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/ExtensionRangeOptions.scala:23: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/ExtensionRangeOptions.scala:40: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/FieldOptions.scala:94: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/FieldOptions.scala:129: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/FileOptions.scala:128: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/FileOptions.scala:199: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/MessageOptions.scala:81: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/MessageOptions.scala:110: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/MethodOptions.scala:32: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/MethodOptions.scala:55: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/OneofOptions.scala:23: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/OneofOptions.scala:40: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/ServiceOptions.scala:30: error: value += is not a member of Int
  Expression does not convert to assignment because:
    value serializedSize is not a member of scalapb.UnknownFieldSet
    expansion: __size = __size.+(unknownFields.<serializedSize: error>)
      __size += unknownFields.serializedSize
             ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/google/protobuf/descriptor/ServiceOptions.scala:50: error: value writeTo is not a member of scalapb.UnknownFieldSet
      unknownFields.writeTo(_output__)
                    ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/trueaccord/scalapb/scalapb/ScalapbProto.scala:48: error: value lengthDelimitedLens is not a member of object scalapb.UnknownFieldSet.Field
    _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(1020, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => _root_.com.trueaccord.scalapb.GeneratedExtension.readMessageFromByteString(com.trueaccord.scalapb.scalapb.ScalaPbOptions)(__valueIn)}, {__valueIn => __valueIn.toByteString})
                                                                                                                        ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/trueaccord/scalapb/scalapb/ScalapbProto.scala:50: error: value lengthDelimitedLens is not a member of object scalapb.UnknownFieldSet.Field
    _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(1020, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => _root_.com.trueaccord.scalapb.GeneratedExtension.readMessageFromByteString(com.trueaccord.scalapb.scalapb.MessageOptions)(__valueIn)}, {__valueIn => __valueIn.toByteString})
                                                                                                                        ^
bazel-out/local-fastbuild/bin/common/tmp4695179438388681337/com/trueaccord/scalapb/scalapb/ScalapbProto.scala:52: error: value lengthDelimitedLens is not a member of object scalapb.UnknownFieldSet.Field
    _root_.com.trueaccord.scalapb.GeneratedExtension.forOptionalUnknownField(1020, _root_.scalapb.UnknownFieldSet.Field.lengthDelimitedLens)({__valueIn => _root_.com.trueaccord.scalapb.GeneratedExtension.readMessageFromByteString(com.trueaccord.scalapb.scalapb.FieldOptions)(__valueIn)}, {__valueIn => __valueIn.toByteString})
                                                                                                                        ^
21 errors found
21 errors found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:256)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:68)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:125)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
Target //common:common_scala_proto failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.749s, Critical Path: 10.64s
```

Building `scalapb` works fine. Running `bazel build scalapb:scalapb_scala_proto`:
```
INFO: Found 1 target...
Target //scalapb:scalapb_scala_proto up-to-date:
  bazel-bin/scalapb/scalapb_scala_proto.jar
INFO: Elapsed time: 0.107s, Critical Path: 0.00s
```

**Comment by azymnis** [comment]
@BlueDragonX seems like this is missing the scalapb proto generated classes. Can I ask you a favor? Would you be able to create a repo that minimally shows this error and send it to me so that I can make it work?

**Comment by BlueDragonX** [comment]
@azymnis I've done so here: https://github.com/zenreach/bazel-examples.

Running `bazel build events:events_scala_proto` will result in the above error.

The `master` branch vendors the well known protobufs. This allows `scalapb_proto_library` to work when running `bazel build scalapb:scalapb_scala_protos`. I have a branch called `rgb/well_known_protos` which removes this vendoring. This results in `scalapb_proto_library` failing to find `descriptor.proto`.

The `proto_library` and `java_proto_library` targets all work as expected. The `go` targets don't yet work as I'm dealing with similar issues there.

**Comment by azymnis** [comment]
@BlueDragonX thank you! I'll keep digging and get back to you asap

**Comment by BlueDragonX** [comment]
@azymnis: It looks like @nmurthy was able to solve the problem. He's got a branch here: https://github.com/zenreach/bazel-examples/tree/nikhil/scala_proto_tests

**Comment by azymnis** [comment]
@BlueDragonX @nmurthy thanks for fixing my crappy code guys

**Comment by johnynek** [comment]
Guys,

I'm happy to merge the fix. Are all the fixes in PRs now?

**Comment by BlueDragonX** [comment]
This was fixed by https://github.com/bazelbuild/rules_scala/pull/318. The other issue we were having was due to improperly ordering our workspace rules.
