### ISSUE TITLE
CI build broken since 10/20/17

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_scala#323]
https://ci.bazel.io/job/rules_scala/933/

Log: 
```
[variation=,node=ubuntu_16.04-x86_64] ERROR: /home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/test/BUILD:213:1: in scala_library rule //test:MixJavaScalaLib: 
[variation=,node=ubuntu_16.04-x86_64] Traceback (most recent call last):
[variation=,node=ubuntu_16.04-x86_64] 	File "/home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/test/BUILD", line 213
[variation=,node=ubuntu_16.04-x86_64] 		scala_library(name = 'MixJavaScalaLib')
[variation=,node=ubuntu_16.04-x86_64] 	File "/home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/scala/scala.bzl", line 668, in _scala_library_impl
[variation=,node=ubuntu_16.04-x86_64] 		_lib(ctx, True)
[variation=,node=ubuntu_16.04-x86_64] 	File "/home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/scala/scala.bzl", line 598, in _lib
[variation=,node=ubuntu_16.04-x86_64] 		_compile_or_empty(ctx, cjars, srcjars, non_macro_lib, <3 more arguments>)
[variation=,node=ubuntu_16.04-x86_64] 	File "/home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/scala/scala.bzl", line 338, in _compile_or_empty
[variation=,node=ubuntu_16.04-x86_64] 		_compile(ctx, jars, srcjars, buildijar, <3 more arguments>)
[variation=,node=ubuntu_16.04-x86_64] 	File "/home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/scala/scala.bzl", line 278, in _compile
[variation=,node=ubuntu_16.04-x86_64] 		try_to_compile_java_jar(ctx, scala_output, all_srcjars, java_s..., ...)
[variation=,node=ubuntu_16.04-x86_64] 	File "/home/ci/workspace/rules_scala-variation=,node=ubuntu_16.04-x86_64/scala/scala.bzl", line 296, in try_to_compile_java_jar
[variation=,node=ubuntu_16.04-x86_64] 		java_common.create_provider(compile_time_jars = [scala_outpu...], ... [])
[variation=,node=ubuntu_16.04-x86_64] In java_common.create_provider the value of use_ijar is True. Make sure the first argument of the function is the ctx.actions object.
[variation=,node=ubuntu_16.04-x86_64] ERROR: Analysis of target '//test:MixJavaScalaLibBinary' failed; build aborted: Analysis of target '//test:MixJavaScalaLib' failed; build aborted.
```

**Comment by ittaiz** [comment]
We know, there are two other tickets about this.
It's very high on my priority list.

**Comment by jin** [comment]
Oops, sorry for dupe. Closing.
