### ISSUE TITLE
Transitive Java dependencies not working

### ISSUE THREAD

**Issue by SirCmpwn** [bazelbuild/rules_scala#334]
Minimum reproducable test case: https://git.sr.ht/~sircmpwn/rules-scala/

Result:

```
~/s/t/rules_scala > bazel build ...
INFO: Found 3 targets...
ERROR: /home/sircmpwn/sources/test_cases/rules_scala/library_a/BUILD:3:1: scala //library_a:library_a failed (Exit 1).
library_a/ExampleA.scala:8: error: Class library_c.ExampleC not found - continuing with a stub.
) extends ExampleB
          ^
one error found
one error found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:256)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:68)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:125)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
INFO: Elapsed time: 1.061s, Critical Path: 1.01s
```

**Comment by johnynek** [comment]
I don't see the bug. Can you clarify? Bazel is not transitive in this way. There are two solutions here. 

1. add library a to the `exports` of library b.
2. add an explicit dependency on library a.

This blog has some notes: https://blog.bazel.build/2017/06/28/sjd-unused_deps.html

**Comment by SirCmpwn** [comment]
This works, thanks for clarifying.
