### ISSUE TITLE
Worker crash: value already present

### ISSUE THREAD

**Issue by arjantop** [bazelbuild/rules_scala#420]
I am converting a project to bazel with rules_scala and I got this error a couple of times already:

```
java.lang.IllegalArgumentException: value already present: /app/3rdparty/jvm/org/xerial/snappy
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$WatcherFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:293)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$WatcherFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:263)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.registerSubDirectoriesAndReturnContents(WatchServiceDiffAwareness.java:258)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.collectChanges(WatchServiceDiffAwareness.java:242)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.getCurrentView(WatchServiceDiffAwareness.java:124)
	at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(DiffAwarenessManager.java:92)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:322)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:247)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:539)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:160)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:381)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:348)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:74)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:489)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: value already present: /app/3rdparty/jvm/org/xerial/snappy
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$WatcherFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:293)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness$WatcherFileVisitor.preVisitDirectory(WatchServiceDiffAwareness.java:263)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.registerSubDirectoriesAndReturnContents(WatchServiceDiffAwareness.java:258)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.collectChanges(WatchServiceDiffAwareness.java:242)
	at com.google.devtools.build.lib.skyframe.WatchServiceDiffAwareness.getCurrentView(WatchServiceDiffAwareness.java:124)
	at com.google.devtools.build.lib.skyframe.DiffAwarenessManager.getDiff(DiffAwarenessManager.java:92)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.handleDiffs(SequencedSkyframeExecutor.java:322)
	at com.google.devtools.build.lib.skyframe.SequencedSkyframeExecutor.sync(SequencedSkyframeExecutor.java:247)
	at com.google.devtools.build.lib.runtime.CommandEnvironment.setupPackageCache(CommandEnvironment.java:539)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:160)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:381)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:348)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:74)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:489)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:218)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:851)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:916)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
```

I did not yet have time to investigate.

**Comment by johnynek** [comment]
what version of bazel, what OS?

This looks like a bazel issue, not something in the rules. You might want to file it with bazel. I have not seen this issue before.

**Comment by arjantop** [comment]
You are right that this might actually be the bazel issue, since the only thing used was rules_scala I somehow assumed that rules_scala have the issue. If it actually happens again I will investigate the cause and submit the ticket to bazel. Cosing this.
