### ISSUE TITLE
rules_scala fails under --all_incompatible_changes: `+` operator on a depset is forbidden

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_scala#430]
```
$ bazel build //jvm-toxcore-c/... --all_incompatible_changes
Loading:
Loading: 0 packages loaded
ERROR: /private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/third_party/plugin/src/main/BUILD:5:1: in scala_library_for_plugin_bootstrapping rule @io_bazel_rules_scala//third_party/plugin/src/main:dependency_analyzer:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/third_party/plugin/src/main/BUILD", line 5
		scala_library_for_plugin_bootstrapping(name = 'dependency_analyzer')
	File "/private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/scala/scala.bzl", line 733, in _scala_library_impl
		_lib(ctx, True)
	File "/private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/scala/scala.bzl", line 660, in _lib
		_collect_jars_from_common_ctx(ctx)
	File "/private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/scala/scala.bzl", line 621, in _collect_jars_from_common_ctx
		collect_jars(((ctx.attr.deps + auto_deps) + e...), ...)
	File "/private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/scala/scala.bzl", line 597, in collect_jars
		_collect_jars_when_dependency_analyzer_is_off(dep_targets)
	File "/private/var/tmp/_bazel_iphy/178403b66d944445b84ccba31dd03db8/external/io_bazel_rules_scala/scala/scala.bzl", line 549, in _collect_jars_when_dependency_analyzer_is_off
		compile_jars += java_provider.compile_jars
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//jvm-toxcore-c:AudioReceiveFrameCallbackTest' failed; build aborted: Analysis of target '@io_bazel_rules_scala//third_party/plugin/src/main:dependency_analyzer' failed; build aborted
INFO: Elapsed time: 0.196s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by iphydf** [comment]
There are several more issues:
```
external/io_bazel_rules_scala/scala/scala.bzl", line 405, in write_manifest
                ctx.file_action(output = ctx.outputs.manifest, con...)
Use ctx.actions.write instead of ctx.file_action.
```
and
```
external/io_bazel_rules_scala/scala/scala.bzl", line 354, in _compile_or_empty
                len(srcjars)
depset is not iterable. You may use `len(<depset>.to_list())` instead.
```

**Comment by johnynek** [comment]
PRs welcome especially when they don't close off old bazel versions. I somewhat would like to support as many versions as we reasonable can without ugly hacks and always supporting the latest version of bazel.

**Comment by ittaiz** [comment]
I think there is a “cost” here Oscar we need to acknowledge since keeping
up to date with this flag can mean foregoing old versions and not keeping
up means that there is an interim of time where we don’t support
latest(once a deprecated feature is removed).
To be clear I think we should run with this flag (there is an existing
issue about it).

And I definitely agree about PRs welcome :)

**Comment by johnynek** [comment]
So, why don't we start doing this:

1) run with this flag set from now on.
2) start making branches of the rules for each bazel. We won't necessarily cherry-pick all the changes, but we can try for a while.
3) make master always working cleanly with the latest released versions.

What do you think of this plan?

**Comment by ittaiz** [comment]
SGTM
We can also encourage users of old versions to contribute in the cherry-picking if it's important for them
