### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Implementing class

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_scala#512]
Exactly as of https://github.com/bazelbuild/rules_scala/commit/7456a0b5a945ff8b09530c6601dced9ad46e58be (bisected - it works before this one, not after), my build is broken:

```
ERROR: /home/iphydf/code/toktok-stack/jvm-toxcore-c/BUILD.bazel:181:2: scala //jvm-toxcore-c:ToxGetPortExceptionTest failed (Exit 1)
jvm-toxcore-c/src/test/java/im/tox/tox4j/core/exceptions/ToxGetPortExceptionTest.scala:9: error: Symbol 'type org.scalatest.package.Assertion' is missing from the classpath.
This symbol is required by 'method im.tox.tox4j.testing.ToxTestMixin.interceptWithTox'.
Make sure that type Assertion is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'ToxTestMixin.class' was compiled against an incompatible version of org.scalatest.package.
    interceptWithTox(ToxGetPortException.Code.NOT_BOUND)(
    ^
one error found
```

This is the code: https://github.com/TokTok/jvm-toxcore-c/blob/master/BUILD.bazel. The targets that broke are the scala_tests on line 181. I don't currently have a minimal repro case. I'm happy to help by testing proposed fixes.

**Comment by iphydf** [comment]
Separately, the same PR also broke the tests in https://github.com/TokTok/jvm-toxcore-api/blob/master/BUILD.bazel#L18 but at runtime, not at compile time. I see this error:

```
INFO: From Testing //jvm-toxcore-api:jvm-toxcore-api-test:
==================== Test output for //jvm-toxcore-api:jvm-toxcore-api-test:
Discovery starting.
Discovery completed in 104 milliseconds.
Run starting. Expected test count is: 0
ToxFileIdTest:
im.tox.tox4j.core.data.ToxFileIdTest *** ABORTED *** (0 milliseconds)
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: im.tox.tox4j.core.data.ToxFileIdTest
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1165)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1250)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:19)
  Cause: java.lang.AbstractMethodError: im.tox.tox4j.core.data.ToxFileIdTest.PropertyCheckConfiguration()Lorg/scalatest/prop/Configuration$PropertyCheckConfiguration$;
  at org.scalatest.prop.Configuration$class.$init$(Configuration.scala:456)
  at im.tox.core.ModuleCompanionTest.<init>(ModuleCompanionTest.scala:7)
  at im.tox.core.typesafe.WrappedValueCompanionTest.<init>(WrappedValueCompanionTest.scala:6)
  at im.tox.core.typesafe.ByteArrayCompanionTest.<init>(ByteArrayCompanionTest.scala:4)
  at im.tox.core.typesafe.FixedSizeByteArrayCompanionTest.<init>(FixedSizeByteArrayCompanionTest.scala:4)
  at im.tox.core.typesafe.KeyCompanionTest.<init>(KeyCompanionTest.scala:8)
  at im.tox.tox4j.core.data.ToxFileIdTest.<init>(ToxFileIdTest.scala:15)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:66)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1165)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1250)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:19)
```

**Comment by iphydf** [comment]
You're right. One of the maven_jars implicitly defines another maven_jar that's a different version of scalatest (2.2.6 vs. 3.0.5). This is surprising behaviour of maven_jar. I thought it explicitly did not do this for security reasons. The "scalatest" version is not SHA-1 checked.

**Comment by iphydf** [comment]
Now I'm getting "java.lang.IncompatibleClassChangeError: Implementing class". I'll see if there are any other double versions.

**Comment by iphydf** [comment]
https://github.com/iphydf/repro512 reproducing test case (somewhat minimised).

Travis build: https://travis-ci.org/iphydf/repro512/jobs/389459260#L621

**Comment by iphydf** [comment]
Any news on this? Do I need to further reduce the test case?

**Comment by johnynek** [comment]
Sadly, I think the right way to think about this project as a collective of people working to use scala with bazel in enterprise settings and helping each other in that process. I really haven't had time to look at your issue. I am happy to spend a few minutes usually, but deeper dives have trouble getting scheduled.

I am working on fixing issues related to very large classpaths and issues with the thrift support at the moment. Sorry I haven't had more time to spare.

**Comment by iphydf** [comment]
I've minimised it to a grand total of 1 effective line of Scala. It breaks on PropertyChecks. If I remove the `with PropertyChecks` inheritance, it stops failing. I'm stuck here now. Any advice on where I could continue looking?

WORKSPACE:
```python
workspace(name = "toktok")

# Maven dependencies
# =========================================================

maven_jar(
    name = "org_scalacheck_scalacheck",
    artifact = "org.scalacheck:scalacheck_2.11:1.13.4",
    sha1 = "7845816647d5a80d30e5a71862b31f3fee894549",
)

# Scala toolchain
# =========================================================

RULES_SCALA_VERSION = "1865e6396ff38a9b0c4b435c683d3d7c193c4c0e"

http_archive(
    name = "io_bazel_rules_scala",
    sha256 = "0f0cdfb141304409023d7afaa53235361952e0aa26078c397f9f10b51d6808e6",
    strip_prefix = "rules_scala-%s" % RULES_SCALA_VERSION,
    urls = ["https://github.com/bazelbuild/rules_scala/archive/%s.zip" % RULES_SCALA_VERSION],
)

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")

scala_register_toolchains()

scala_repositories()
```

mytest/BUILD.bazel:
```python
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_test")

scala_test(
    name = "my_test",
    srcs = ["MyTest.scala"],
    deps = ["@org_scalacheck_scalacheck//jar:file"],
)
```

mytest/MyTest.scala:
```scala
import org.scalatest.FunSuite
import org.scalatest.prop.PropertyChecks

final class MyTest extends FunSuite with PropertyChecks
```

**Comment by iphydf** [comment]
After building once, I can reproduce the exception using this script: https://gist.github.com/iphydf/883ea5b982b1c3aaa7c25062de5f290f

The only things not built in this script (because it's a lot of work) are runner.jar and test_reporter.jar.

**Comment by iphydf** [comment]
http://central.maven.org/maven2/org/scalatest/scalatest_2.11/2.2.6/scalatest_2.11-2.2.6.pom

scalatest needs a very specific version of scalacheck: 1.12.4. Changing that fixes it.
