### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_scala#644]
I'd like to be able to build rules_scala with `--all_incompatible_changes`

e.g. `cd rules_scala && bazel test scala:all --all_incompatible_changes`

It may not be possible to fix every issue now due to transitive dependencies, but we should try to fix the issues from this repository.

**Comment by xingao267** [comment]
This is blocking turn on --all_incompatible_changes for rules_docker.

Traceback (most recent call last):
	File "/usr/local/google/home/xingao/.cache/bazel/_bazel_xingao/459658d023448dae1285a534aa3be713/external/io_bazel_rules_scala_scala_compiler/BUILD", line 9
		scala_import(name = 'io_bazel_rules_scala_scala_compiler')
	File "/usr/local/google/home/xingao/.cache/bazel/_bazel_xingao/459658d023448dae1285a534aa3be713/external/io_bazel_rules_scala/scala/scala_import.bzl", line 27, in _scala_import_impl
		struct(scala = struct(outputs = struct(...)), ...)])
	File "/usr/local/google/home/xingao/.cache/bazel/_bazel_xingao/459658d023448dae1285a534aa3be713/external/io_bazel_rules_scala/scala/scala_import.bzl", line 32, in struct
		_create_provider(current_jars, transitive_runtime_j..., <5 more arguments>)
	File "/usr/local/google/home/xingao/.cache/bazel/_bazel_xingao/459658d023448dae1285a534aa3be713/external/io_bazel_rules_scala/scala/scala_import.bzl", line 73, in _create_provider
		java_common.create_provider(use_ijar = False, compile_time_jar...]), <3 more arguments>)
create_provider is deprecated and cannot be used when --incompatible_disallow_legacy_javainfo is set. Please migrate to the JavaInfo constructor.
ERROR: Analysis of target '//container:image_test' failed; build aborted: Analysis of target '@io_bazel_rules_scala_scala_compiler//:io_bazel_rules_scala_scala_compiler' failed; build aborted

**Comment by ittaiz** [comment]
Hey,
I’d also like to get there.
The JavaInfo move is complicated since we have a big ball of mud in that
aspect. I hope to tackle this in the next few weeks but I estimate a
correct fix would take me 1-2 full days.

The change is not drop in at all.

**Comment by laurentlb** [comment]
cc @iirina

**Comment by johnynek** [comment]
@ittaiz we also had the issue that we had to make a scala provider to deal with Intellij since the JavaInfo wouldn’t let us do something we needed. Do you remember what that was? I don’t use IntelliJ but I’d like to also remove that hack.

I made the issue #466 to document this.

**Comment by ittaiz** [comment]
Don't remember it but don't worry, Intellij regression isn't an option for
us :)
Almost everyone uses it and are highly sensitive to it breaking

**Comment by laurentlb** [comment]
Based on the latest CI run (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/28#3f510def-b9f1-49c8-9079-32ed26b1f2b7), migration is needed for the following flags:

  * --incompatible_depset_is_not_iterable
  * --incompatible_disable_deprecated_attr_params
  * --incompatible_disable_legacy_proto_provider
  * --incompatible_disable_proto_source_root
  * --incompatible_no_support_tools_in_action_inputs
  * --incompatible_remap_main_repo
  * --incompatible_use_toolchain_providers_in_java_common

The depset changes have been around for a while. Could you take a look at it?
https://docs.bazel.build/versions/master/skylark/depsets.html

**Comment by laurentlb** [comment]
Any update on this?
Can you look at these flags?


* `--incompatible_depset_is_not_iterable`. Your code needs to be updated. The simplest fix is to add `.to_list()` where needed.
* `--incompatible_disable_deprecated_attr_params`. Try updating your dependency on Protobuf (use 3.7.1).
* `--incompatible_disallow_legacy_java_provider`
* `--incompatible_no_support_tools_in_action_inputs`. Your code needs to be updated (should be easy).

Thanks
