### ISSUE TITLE
Do not generate scala code for proto_library deps

### ISSUE THREAD

**Issue by simuons** [bazelbuild/rules_scala#659]
Given build file

```
load("@io_bazel_rules_scala//scala_proto:scala_proto.bzl", "scala_proto_srcjar", "scala_library")

proto_library(
    name = "message1_proto",
    srcs = ["message-1.proto"],
    deps = ["@com_google_protobuf//:any_proto"])

proto_library(
    name = "message2_proto",
    srcs = ["message-2.proto"],
    deps = ["@com_google_protobuf//:any_proto"])

scala_proto_srcjar(
    name = "message1_proto_scala",
    generator = "@io_bazel_rules_scala//src/scala/scripts:scalapb_generator",
    deps = [":message1_proto"])

scala_proto_srcjar(
    name = "message2_proto_scala",
    generator = "@io_bazel_rules_scala//src/scala/scripts:scalapb_generator",
    deps = [":message2_proto"])

scala_library(
    name = "lib_scala",
    srcs = [
        ":message1_proto_scala", 
        ":message2_proto_scala"],
    deps = [
        "@com_google_protobuf//:protobuf_java",
        "@scala_proto_rules_scalapb_lenses",
        "@scala_proto_rules_scalapb_runtime"])
```

`scala_library` target fails with

```
scala //:lib_scala failed (Exit 1) scalac failed: error executing command bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/darwin-fastbuild/bin/lib_scala_scalac_worker_input

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/darwin-fastbuild/bin/tmp561837293313661215/com/google/protobuf/any/Any.scala:119: error: Any is already defined as case class Any
final case class Any(
                 ^
bazel-out/darwin-fastbuild/bin/tmp561837293313661215/com/google/protobuf/any/AnyProto.scala:8: error: AnyProto is already defined as object AnyProto
object AnyProto extends _root_.scalapb.GeneratedFileObject {
       ^
two errors found
two errors found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:242)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:67)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
```

this happens because both `proto_library` depends on `@com_google_protobuf//:any_proto` and both `scala_proto_srcjar` generates scala code for it.

`protoc` command looks like this

```
protoc-jar: executing: [/var/folders/6w/7lqypyx94r161fg4g11fmkqh0000gn/T/protocjar18054286096154112977/bin/protoc.exe, --plugin=protoc-gen-scala=/var/folders/6w/7lqypyx94r161fg4g11fmkqh0000gn/T/protocbridge15240789923811538906, --scala_out=/var/folders/6w/7lqypyx94r161fg4g11fmkqh0000gn/T/bazelscalapb4273461064147549483, --proto_path=external/com_google_protobuf, --proto_path=., -Igoogle/protobuf/any.proto=bazel-out/darwin-fastbuild/genfiles/external/com_google_protobuf/google/protobuf/any.proto, -Imessage-1.proto=message-1.proto, bazel-out/darwin-fastbuild/genfiles/external/com_google_protobuf/google/protobuf/any.proto, message-1.proto]
```

both `any.proto` and `message-1.proto` are passed as inputs to `protoc` which cause scala code generation.

I think that `proto_library` `deps` should go to `--proto_path` and only `srcs` should be passed as inputs to `protoc`.

**Comment by johnynek** [comment]
@azymnis have you hit this?

It did seem that the dependency handling was different in proto than thrift. I didn't take time to verify it when I saw it last.

**Comment by ittaiz** [comment]
Btw,
Simonas will also send a fix for this soon.
We’re hitting this internally.

**Comment by azymnis** [comment]
@johnynek @ittaiz sorry for not responding earlier! Haven't used this rule in a while so have not seen this issue

**Comment by azymnis** [comment]
Oh and sorry for adding this bug in here in the first place :|

**Comment by simuons** [comment]
Hi,

after I started working on this I realised that this actually isn't a bug. It behaves as expected according to `proto_library`. Given example represents our edge case which we gonna solve by other means. I'm sorry for the noise. Cheers.
