### ISSUE TITLE
Protobuf rules fail under Bazel 0.21

### ISSUE THREAD

**Issue by samschlegel** [bazelbuild/rules_scala#664]
Based on https://github.com/grpc/grpc/issues/17564 this is due to the protobuf dependency needing an update to 3.6.1.3

Error:
```
ERROR: .../external/com_google_protobuf/BUILD:573:1: Traceback (most recent call last):
	File ".../external/com_google_protobuf/BUILD", line 573
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File ".../external/com_google_protobuf/protobuf.bzl", line 269, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File ".../external/com_google_protobuf/protobuf.bzl", line 269, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: .../external/com_google_protobuf/BUILD:355:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: .../external/com_google_protobuf/BUILD:355:1: Target '@com_google_protobuf//:msvc' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: .../protobuf/BUILD:3:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
```

**Comment by samschlegel** [comment]
Looks like it was an old version of rules_go
