### ISSUE TITLE
Scrooge Error when defining Thrift exception

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_scala#845]
I noticed when a Thrift file defines an exception, scrooge throws an exception:

For example adding:

```
exception FooBar {
  1: string code
}
```

to `test/src/main/scala/scalarules/test/twitter_scrooge/thrift/thrift2/thrift3/Thrift3.thrift` results in this:

```
ERROR: /absolute/path/to/test/src/main/scala/scalarules/test/twitter_scrooge/thrift/thrift2/thrift3/BUILD:4:1: Couldn't build file test/src/main/scala/scalarules/test/twitter_scrooge/thrift/thrift2/thrift3/thrift3_scrooge.jar: scala //test/src/main/scala/scalarules/test/twitter_scrooge/thrift/thrift2/thrift3:thrift3 failed (Exit 1)
bazel-out/darwin-fastbuild/bin/test/src/main/scala/scalarules/test/twitter_scrooge/thrift/thrift2/thrift3/tmp4446905357582031766/scalarules/test/twitter_scrooge/thrift/thrift2/thrift3/FooBar.scala:171: error: object finagle is not a member of package com.twitter
  extends ThriftException with com.twitter.finagle.SourcedException with ThriftStruct
                                           ^
one error found
one error found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:244)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:69)
	at io.bazel.rulesscala.worker.GenericWorker.runPersistentWorker(GenericWorker.java:45)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:111)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
```

**Comment by johnynek** [comment]
so, not everyone uses finagle (e.g. data uses of thrift which aren't about services). I'm reluctant to change the classpaths of everyone using the rules.

The alternate way is to configure which jars come in by changing the bind here:
https://github.com/bazelbuild/rules_scala/blob/master/twitter_scrooge/twitter_scrooge.bzl#L69

in your own repo, e.g. make that bind point to `scala_library` that exports both scrooge_core and finagle.

**Comment by KaoruDev** [comment]
I'm going to try out your suggestion @johnynek gonna keep this open so I can ask you questions on how to go about it. I'll close it out once I have it working and contribute documentation for others to learn. How does that sound?
